<?php
require __DIR__.'/config/bootstrap.php';
if(is_logged_in()) redirect('index.php');
$error=''; verify_csrf();
if($_SERVER['REQUEST_METHOD']==='POST'){
    $identity=trim($_POST['identity']??'');$password=$_POST['password']??'';
    try{$q=db()->prepare("SELECT id,username,email,password,role,status FROM users WHERE (email=? OR username=?) LIMIT 1");$q->execute([$identity,$identity]);$user=$q->fetch();
        if($user&&$user['status']==='active'&&password_verify($password,$user['password'])){session_regenerate_id(true);unset($user['password']);$_SESSION['user']=$user;$_SESSION['last_activity']=time();log_activity('Login','Signed in');redirect('index.php');}
        $error='Those sign-in details don’t match an active account.';
    }catch(Throwable){$error='EMS could not connect to its database. Import database/ems.sql and check config/database.php.';}
}
$flashes=take_flashes();
?><!doctype html><html lang="en" data-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Sign in · EMS</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="<?=e(app_url('assets/css/style.css'))?>"></head><body class="login-page"><main class="login-shell"><section class="login-art"><a class="brand" href="<?=e(app_url(''))?>"><span class="brand-mark">E</span><span>EMS<span class="brand-sub">PEOPLE SYSTEMS</span></span></a><div class="art-copy"><span class="eyebrow">PEOPLE, IN GOOD SYNC</span><h1>Make work<br>work better.</h1><p>A calm, clear space for your people operations.</p></div><div class="art-orbit orbit-one"></div><div class="art-orbit orbit-two"></div><span class="art-note">EMPLOYEE EXPERIENCE · 01</span></section><section class="login-panel"><button class="theme-toggle login-theme" type="button" aria-label="Toggle theme">◐</button><div class="login-card"><span class="eyebrow">WELCOME BACK</span><h2>Sign in to EMS</h2><p class="muted-text">Use your work account to continue.</p><?php foreach($flashes as [$t,$m]):?><div class="toast <?=$t?>"><?=e($m)?></div><?php endforeach;?><?php if($error):?><div class="toast danger"><?=e($error)?></div><?php endif;?><form method="post" class="stack-form" data-loading><?=csrf_field()?><label>Email or username<input name="identity" autocomplete="username" required autofocus value="<?=e($_POST['identity']??'')?>" placeholder="you@company.com"></label><label>Password<span class="password-wrap"><input id="password" type="password" name="password" autocomplete="current-password" required placeholder="Enter your password"><button class="password-toggle" type="button" data-password="password">Show</button></span></label><div class="form-row between"><label class="check-label"><input type="checkbox" name="remember"> Keep me signed in</label><span class="small-note">Secure access</span></div><button class="button primary full" type="submit"><span>Sign in</span><span class="button-spinner"></span></button></form><div class="login-foot">Protected workspace <span>·</span> EMS 1.0</div></div></section></main><script src="<?=e(app_url('assets/js/app.js'))?>"></script></body></html>
